// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"o2b.com.br/whatsAppApi/models"
)

// GetMessagesOKCode is the HTTP code returned for type GetMessagesOK
const GetMessagesOKCode int = 200

/*GetMessagesOK just a test for igor

swagger:response getMessagesOK
*/
type GetMessagesOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Message `json:"body,omitempty"`
}

// NewGetMessagesOK creates GetMessagesOK with default headers values
func NewGetMessagesOK() *GetMessagesOK {

	return &GetMessagesOK{}
}

// WithPayload adds the payload to the get messages o k response
func (o *GetMessagesOK) WithPayload(payload []*models.Message) *GetMessagesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get messages o k response
func (o *GetMessagesOK) SetPayload(payload []*models.Message) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMessagesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Message, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*GetMessagesDefault generic error response

swagger:response getMessagesDefault
*/
type GetMessagesDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetMessagesDefault creates GetMessagesDefault with default headers values
func NewGetMessagesDefault(code int) *GetMessagesDefault {
	if code <= 0 {
		code = 500
	}

	return &GetMessagesDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get messages default response
func (o *GetMessagesDefault) WithStatusCode(code int) *GetMessagesDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get messages default response
func (o *GetMessagesDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get messages default response
func (o *GetMessagesDefault) WithPayload(payload *models.Error) *GetMessagesDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get messages default response
func (o *GetMessagesDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMessagesDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
