// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"o2b.com.br/whatsAppApi/models"
)

// NewSendMessageParams creates a new SendMessageParams object
// no default values defined in spec.
func NewSendMessageParams() SendMessageParams {

	return SendMessageParams{}
}

// SendMessageParams contains all the bound params for the send message operation
// typically these are obtained from a http.Request
//
// swagger:parameters sendMessage
type SendMessageParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*create a new message
	  Required: true
	  In: body
	*/
	Body *models.Message
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewSendMessageParams() beforehand.
func (o *SendMessageParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Message
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("body", "body", ""))
			} else {
				res = append(res, errors.NewParseError("body", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Body = &body
			}
		}
	} else {
		res = append(res, errors.Required("body", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
