// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"o2b.com.br/whatsAppApi/models"
)

// SendMessageCreatedCode is the HTTP code returned for type SendMessageCreated
const SendMessageCreatedCode int = 201

/*SendMessageCreated Created

swagger:response sendMessageCreated
*/
type SendMessageCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Message `json:"body,omitempty"`
}

// NewSendMessageCreated creates SendMessageCreated with default headers values
func NewSendMessageCreated() *SendMessageCreated {

	return &SendMessageCreated{}
}

// WithPayload adds the payload to the send message created response
func (o *SendMessageCreated) WithPayload(payload *models.Message) *SendMessageCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the send message created response
func (o *SendMessageCreated) SetPayload(payload *models.Message) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SendMessageCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
