// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// SyncCreatedCode is the HTTP code returned for type SyncCreated
const SyncCreatedCode int = 201

/*SyncCreated Created

swagger:response syncCreated
*/
type SyncCreated struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewSyncCreated creates SyncCreated with default headers values
func NewSyncCreated() *SyncCreated {

	return &SyncCreated{}
}

// WithPayload adds the payload to the sync created response
func (o *SyncCreated) WithPayload(payload interface{}) *SyncCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the sync created response
func (o *SyncCreated) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SyncCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
