// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// SyncHandlerFunc turns a function with the right signature into a sync handler
type SyncHandlerFunc func(SyncParams) middleware.Responder

// Handle executing the request and returning a response
func (fn SyncHandlerFunc) Handle(params SyncParams) middleware.Responder {
	return fn(params)
}

// SyncHandler interface for that can handle valid sync params
type SyncHandler interface {
	Handle(SyncParams) middleware.Responder
}

// NewSync creates a new http.Handler for the sync operation
func NewSync(ctx *middleware.Context, handler SyncHandler) *Sync {
	return &Sync{Context: ctx, Handler: handler}
}

/*Sync swagger:route POST /sync api sync

Sync sync API

*/
type Sync struct {
	Context *middleware.Context
	Handler SyncHandler
}

func (o *Sync) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewSyncParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
