// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Whats app integration
//
//  Whatsapp communication API
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 1.0.0
//
//  Consumes:
//    - application/io.goswagger.examples.todo-list.v1+json
//
//  Produces:
//    - application/io.goswagger.examples.todo-list.v1+json
//    - application/json
//
// swagger:meta
package restapi
