resource_types:
- name: helm
  type: docker-image
  source:
    repository: linkyard/concourse-helm-resource

resources:
- name: helm
  type: helm
  source:
    cluster_url: https://172.25.0.2:6443
    cluster_ca: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01UQXhNREU0TURjMU9Wb1hEVE13TVRBd09ERTRNRGMxT1Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTDNnCjFpeFZNRzlYdFAxTU5VQ0FMaG9QS1hiTWtwTzJScEowNHJMa1I4ajhoanlKVUhESzdTWUtkdmZJZnhCeFhHQzAKNUxGYmNkK1MzcDFiaWRiSUtKcGdUbGE5N0tvVWJHYVpwRVV0UURYdXA5dlZ6dEIvUHJ1K1ZwN0ZlcXNXd2ZYbgpvL1pGeEJBY1M2VHVUd1pmTXpEcHJ3aEg2d214MkFBWm81K1VuWnBGRmdScE5kQWY0UVdCMVNwMUtNeklUN040CmgrWlRMbUlFNU80bFI5T2FGalhEWThSV29XRzdrenlkTGgrdXZDeDkvUUxyd1UvOGpCUzdkM2Y2M240K1h5V0QKS0NxdE9SaVFMNGU3RUJBdnI4bENaSlJGMWNUV2pRNUoydVFvZ2cyZThZUVJBbVlDK0ZwNzQwOTlRUE5UTUtaOApmMlJsV1hENmw4Q0ZVcGNkUjNrQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZJeWdyV3ljUGxTRTFBM25WVnFmZFVKQXpRY0xNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFDQUtRWjhhdnJXT3FYajBQWWVJSXVudzV2Q2ZIZWEwV3c4MVhpSHBoV0Y4aHpyR2NhNwpIa1dsMTV1bVZtRXo1Mm5NWmRFdVY2c1cwOWlPOWI3RWVGcFBPVlB3OXJzVkcrYm9rQTNzRkRxcHltQmFiY2krCmVjYjcxbC8waEpnMElzcDNGMHpQMndMdXBQNE5CblExN1Y2ZHF4bzFic1NpOWdydThkNnA1NEMxR0w1RHQxdFEKL1dqVFRYUUtPT016VWx2WDU5TC9NRURkVFhaeHR4YTdweUJNYVZjV1o1VEdHdE4zVDhDaFpNMldldjI5UXQ2SwpqUkNvODZrOUJqNFpTcFZGQ2Z2TUwybEgwSnFuL2o2em92QitRTGNOS2FLZHovTmxvd2JvL25VUkRYSHFraW55CmxibmFDRUxxV2c3Ris4Z2RkbE5YQllwRUtaSUVLK01XWmhvVAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    admin_key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBd1dTNWZYbmJNZ2gyRG9DNG5iZnFWM2FGeTB5bWs0OWZqOHpWdXMzMjY2M3ZIdFYrCmhEaDZzTmt3WkxPbTZ2bzFDN1Uzd241b20rSnc1T21GS2UvdDZscllvMUFCY2tMY2REQkc2QmkrbWZTNWM0U0cKU0czaWl5MmVpaGV5bzN6ekdzUjh3TTN2RCtHQjRFelBJYmZQZ1VFaUpYSmYvWUcrNVFsWE9JOGg0WEpnZDBBMQptbThqSVlxMXlBOGVaQXBLa2x3RUllZVViR2h1SGlpZTdsNmRSK3VKUUpjMitlY29zbDYycGNoZWYycEdhamk2CjU5TFo4cDFJSWppK2pQanFNaWk0M1d5WmNqQmgxU2wxNDFqL1hyOFV6dGNoZjMxbWNCS0M2MXB3SzEydGtHU2EKUmwrT0tPbmZQNVVnbFJUL1dQT3kzeGpLMzRtWWhmT3lXU0xVZVFJREFRQUJBb0lCQUc0d2t0T2dnN2tOUXg3ZQpUdEptZ1JwV2lNTWVLR2M1TUt6QmZDSFV5dFRjSkx1L3p6ZE02dk1xdkwwVDg0NDlBODVvOFoxYTR3VzJ6clpQCks3V0taRmU4YldVWDU4c1B0NFpvSDI2TThzVEx3SUxHUnJDc0U0RlRlOXFZeUFzSTNZY3AzeDhIOXlkb1NOVGgKVHIrYWVKdmYzYkhTYWtrS0RSZDQ2LzVvNTFnSkVIZFhncHo3Wk93WWw2YmF1Y08vWDNMTE8yZDRuUmRQQ3hDNgpuUmpjL2wza0w0aGRFbFVBRGJ6Nkp6K21WOWF3M0dxRHBxUis0azArZDZYTUJkeHEwckNTWFlXTUM0MkRnMnhICjlyQWYyTFVSWXN4cXVkbUprTkdZZ0FHa2t0dEFMVGlKY2dRVFlqc3BHR0p4QU12N2xLOHJQTW45NDBpdHNOZFUKQ0pEMXdCRUNnWUVBL3JPWkRLbytEdXRUS042YU02VmlXaUR4cHpQUzFSaU8zZnNiSmlrMDA1dW9McldEMWErRwpveHhyMmJBQ2ZoZFB1aEZZb0N3RVVZN1p4Wk1tOFhuZTZGL3RhMUtONVYyU2VJYzA3ZUtnWVFxN3h2UTRCczY5ClQ1NXhSOFRGVFVqcXBiVG1Zd3FreGh4TTBEQUdlakVyRHJXZnhCYTdzNE5TN2kyaXRQWEpoajBDZ1lFQXdtRWQKbTFSbEpGNE5XU2Vwdmphb2FUTGtzOFlNMzRYSlBtc0tRREdBK0hpUGFrZS9qTm4wUEw1TG9TK3Q1aE44Uk9hbQp5OWY2OEZKZlRxdy84d25sZ1ZKTDRTSWhpRTlINmRjMkVvSTFhRi9HMW1NbVhiZVc2d0oyQmFlSTgwQ0xTSFlBCnhjZnlmVEhTL3ZyN0FwUlhGQ2NGTEtJdnJ3OWVKcUFva2JEK3B1MENnWUFDakttcmhzaTRQWUxIbGZMVk1ZS2EKaEZubTRvM3B0Q1U1ODVtQitFZWZGcC9JVitqSjZzZmVPaHFhUXpqREtsaVI5RHArMy9Ickh4THU5MW9jY0t2YQpoNXRJeDdyRDRQdm1XUFFlclhZTmdwMytqOU0vdmpJRzZmOFlTTS93eGhvVExveGYwV3QwMERPMG9jWnUwcThyCnBvWEM0TGRnUktBLzRoVU8ycWI1d1FLQmdDNWFFa0ZVSXJwRlkxRjdUOUw0SGJqWVZnazRsU0ZJT2ZFVWZXRkoKYk1QVG0vOXdGSkYxOS9QMFBQeTI3ZlVMZUhyRnRjaXVQRHpLcDhlTzg4RDAvekdUZWx5NVV0MjZhaCt0SGt2VAptUURHdGhleGxSaU1Dd1VIbFRWTCtqQm5sODh6dElOMVpySE1DOUNaOFBsd2ZrTmorcXZtRVJEaHpVWFFzMXZxCnBROFJBb0dBQzErOVlJdFFvRlYvQnk2ZnpQRk1NN0JKRGdHL2JXaHlZR1Zxd2FHRTBoWkIxMW5CVnBWeGJoWEoKL1R5MFF5RmQ5bHB1eFJKc1I5Y0NDSXY3S3pjRFdTemJuWFFpSVFpKzlmSHA5U1NSMENFTUJpaEVsNU5BV3NnbwplanZGTGdXUVRSMzQ4MTcyZUd0ZkxBMkhvZDg3S1JWc3RwT2xMWnMzU1dWb2VBZUNBT009Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
    admin_cert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFekNDQWZ1Z0F3SUJBZ0lJUXFTWHQxanByNDR3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TURFd01UQXhPREEzTlRsYUZ3MHlNVEV3TVRBeE9EQTRNRE5hTURReApGekFWQmdOVkJBb1REbk41YzNSbGJUcHRZWE4wWlhKek1Sa3dGd1lEVlFRREV4QnJkV0psY201bGRHVnpMV0ZrCmJXbHVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXdXUzVmWG5iTWdoMkRvQzQKbmJmcVYzYUZ5MHltazQ5Zmo4elZ1czMyNjYzdkh0VitoRGg2c05rd1pMT202dm8xQzdVM3duNW9tK0p3NU9tRgpLZS90NmxyWW8xQUJja0xjZERCRzZCaSttZlM1YzRTR1NHM2lpeTJlaWhleW8zenpHc1I4d00zdkQrR0I0RXpQCkliZlBnVUVpSlhKZi9ZRys1UWxYT0k4aDRYSmdkMEExbW04aklZcTF5QThlWkFwS2tsd0VJZWVVYkdodUhpaWUKN2w2ZFIrdUpRSmMyK2Vjb3NsNjJwY2hlZjJwR2FqaTY1OUxaOHAxSUlqaStqUGpxTWlpNDNXeVpjakJoMVNsMQo0MWovWHI4VXp0Y2hmMzFtY0JLQzYxcHdLMTJ0a0dTYVJsK09LT25mUDVVZ2xSVC9XUE95M3hqSzM0bVloZk95CldTTFVlUUlEQVFBQm8wZ3dSakFPQmdOVkhROEJBZjhFQkFNQ0JhQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUgKQXdJd0h3WURWUjBqQkJnd0ZvQVVqS0N0Ykp3K1ZJVFVEZWRWV3A5MVFrRE5Cd3N3RFFZSktvWklodmNOQVFFTApCUUFEZ2dFQkFLV0JHS3ozdFRLSVJlbjNTL0htUk5PRUdKc0xwQXhJb0VwTURkcHF4VTJNa1dZOVdYZVd5S0N5CkN5SVU5anduSDloNGRMSjI2bEVTU2RUdjFZQUFFTEZhZXhXNUVKUUdCbHZ4MUNoL28yMkhaR2pReG5mTk55SS8KeUFMclFUY1NXYTVrbWdwbytnN3RqQzJTR3N3MjJXVG1NeXZOZEFRM0pDbkVGT2ZBazNQckxpeVpHenU3WXlyYQpLemJEeWNTTkY3ZTg0R1NxaDdPRldjVVpKNjBna0tiY3BOaERJeUlRRmFuZUZVditsR1pTbExBb3FEbUhYajMvCklaeXNTQlBqVkJkOHpBdDVMbk9oRXVaY3h0VlR3RENFMmliVGtRZ2NWb2psT2J1Tk0vYnVWc25sUWFlckFhaFUKaWZzYmFCQ3NZaTdQMzdmZldIYjRkQnM5MVJOK0s3Zz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    namespace: whatsapp-shared
    insecure_skip_tls_verify: true
    tillerless: true
    tillerless_silent: true
- name: whats-app-api-github
  type: git
  icon: github
  source:
    uri: https://github.com/chalkan3/MyGolangApiTemplate
- name: gopher-sync-github
  type: git
  icon: github
  source:
    uri: https://github.com/chalkan3/worker-sync
- name: gopher-process-github
  type: git
  icon: github
  source:
    uri: https://github.com/chalkan3/GopherCompany

jobs:
- name: deploy-gopher-company
  plan:
  - get: whats-app-api-github
  - get: gopher-sync-github
  - get: gopher-process-github
  - put: helm 
    params:
      repository: gopher-sync-github
      release: sync-workers
      namespace: gopher-workers
      chart:  gopher-sync-github/gophersync/charts/gopher-worker-sync-0.1.0.tgz
      # delete: true



  - put: helm 
    params:
      repository: gopher-process-github
      release: workers-process
      namespace: gopher-company-worker
      recreate_pods: true
      chart:  gopher-process-github/processworker/charts/gopher-worker-process-0.1.0.tgz
      purge: true
      replace: true

# - put: helm 
#     params:
#       repository: whats-app-api-github
#       release: gophers-api
#       recreate_pods: true
#       namespace: gopher-company-api
#       chart:  whats-app-api-github/gopherapichart/charts/gopher-rest-0.1.0.tgz
#       override_values:
#         - key: proxy.useTLS
#           value: false,
#         - key: livenessProbe.httpGet.scheme=
#           value: HTTP,
#         - key: readinessProbe.httpGet.scheme
#           value: HTTP
#         - key: proxy.containerPort
#           value: 9000
#         - key: service.port
#           value: 9000
#         - key: service.internalPort
#           value: 9000
#         - key: service.externalPort
#           value: 9000


